name: Deploy

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

on:
  workflow_dispatch:
  push:
    paths:
      - 'book/**'
      - '{{ cookiecutter.repo_directory }}/**'
      - 'scripts/**'
      - '.github/workflows/deploy.yaml'
      - 'cookiecutter.yaml'

    branches:
      - main

env:
  NCDC_CDO_TOKEN: ${{ secrets.NCDC_CDO_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Print token to file.
      shell: bash -l {0}
      run: |
        echo "Token: ${NCDC_CDO_TOKEN}"
        echo ${NCDC_CDO_TOKEN} > ./book/tutorials/NCEI_Tutorial/token.txt

    - uses: ./.github/actions/buildresources
      with:
        jb-cache: false
        publish-to-gh: true
        jb-save: true
        token:  ${{ secrets.GITHUB_TOKEN }}
        ncdc-cdo-token: ${{ secrets.NCDC_CDO_TOKEN }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
