name: NetlifyPreview

on:
  pull_request_target:
    types: [labeled, synchronize]

env:
  NCDC_CDO_TOKEN: ${{ secrets.NCDC_CDO_TOKEN }}

jobs:
  add-preview:
    runs-on: ubuntu-latest
    # This workflow accesses secrets and checks out a PR, so only run if labelled
    # https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
    if: contains(github.event.pull_request.labels.*.name, 'preview')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: ./.github/actions/buildresources
      with:
        jb-cache: false
        publish-to-gh: false
        jb-save: false
      env:
        NCDC_CDO_TOKEN: ${{ secrets.NCDC_CDO_TOKEN }}

    - name: Deploy Website Preview
      if: always()
      uses: nwtgck/actions-netlify@v3.0
      with:
        publish-dir: './book/_build/html'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        alias: deploy-preview-${{ github.event.number }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        CENSUS_API: ${{ secrets.CENSUS_API }}
        NCDC_CDO_TOKEN: ${{ secrets.NCDC_CDO_TOKEN }}
      timeout-minutes: 1

