name: PagesPreview

permissions:
  contents: write
  pull-requests: write

concurrency: ci-${{ github.ref }}

on:
  pull_request:
    branches:
      - main

jobs:
  pr-preview:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/buildresources
      with:
        jb-cache: true
        publish-to-gh: false
        jb-save: true

    - name: Deploy PR Preview
      uses: rossjrw/pr-preview-action@v1.4.7
      with:
          source-dir: './book/_build/html/'


