name: PagesPreview

on:
  pull_request:
    branches:
      - main

jobs:
  quality-control:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    
    - uses: ./.github/actions/buildresources
      with:
        jb-cache: true
        publish-to-gh: false
        jb-save: true

    - name: Deploy PR Preview
      uses: rossjrw/pr-preview-action@v1.4.7
      with:
          source-dir: './book/_build/html'


